<?php

// This file was generated by running "php bin/console dotenv:dump dev"

return array (
  'APP_ENV' => 'dev',
  'APP_SECRET' => '52bbb0e7ad1f31b8d3804b35e5846aeb',
  'DATABASE_URL' => 'mysql://root:@127.0.0.1:3306/transcar_db?serverVersion=mariadb-10.4.11&charset=utf8',
  'CORS_ALLOW_ORIGIN' => '^https?://(localhost|127\\.0\\.0\\.1)(:[0-9]+)?$',
  'JWT_SECRET_KEY' => '%kernel.project_dir%/config/jwt/private.pem',
  'JWT_PUBLIC_KEY' => '%kernel.project_dir%/config/jwt/public.pem',
  'JWT_PASSPHRASE' => 'dbb40dc7d444bc956c146c3e6b776faa7d079c8ab30a3c0e353842f8de75023a',
  'MAILER_DSN' => 'smtp://noreply@maajabutalent.com:1moins1Equals7@box5600.bluehost.com:465',
  'MESSENGER_TRANSPORT_DSN' => 'doctrine://default?auto_setup=0',
  'CURR_DATE_Y' => date('Y'),
  'CURR_DATE_M' => date('n'),
  'CURR_DATE_D' => date('j'),
);
